pipelines:
  default:
    - parallel:
      - step:
          image: python:3.7
          script:
            - python3.7 setup.py test
      - step:
          image: python:3.6
          script:
            - python3.6 setup.py test
      - step:
          image: python:3.5
          script:
            - python3.5 setup.py test
      - step:
          image: python:3.4
          script:
            - python3.4 setup.py test
      - step:
          image: python:2
          script:
            - python setup.py test
      - step:
          image: pypy:2
          script:
            - pypy setup.py test
      - step:
          image: pypy:3
          script:
            - pypy3 setup.py test
